// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3XPBiyBE99qcN8JglMfGz4CYl3js8JQk',
    appId: '1:331143083816:web:2c4706fd10aed26a39021d',
    messagingSenderId: '331143083816',
    projectId: 'ishtopchi-216b8',
    authDomain: 'ishtopchi-216b8.firebaseapp.com',
    storageBucket: 'ishtopchi-216b8.firebasestorage.app',
    measurementId: 'G-547ZN2D5Z7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF_y_cMVLK6CpvYPcSgmCwGzrmyfC-myY',
    appId: '1:331143083816:android:210c551e524b5db339021d',
    messagingSenderId: '331143083816',
    projectId: 'ishtopchi-216b8',
    storageBucket: 'ishtopchi-216b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBY_ENp1NEt11klhoziKqmjdXDpvJq_iE',
    appId: '1:331143083816:ios:5a8696084952797939021d',
    messagingSenderId: '331143083816',
    projectId: 'ishtopchi-216b8',
    storageBucket: 'ishtopchi-216b8.firebasestorage.app',
    iosClientId: '331143083816-kir3q80qqfi63k3ons61ak2sat8n8pdj.apps.googleusercontent.com',
    iosBundleId: 'torex.top.ishtopchi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBY_ENp1NEt11klhoziKqmjdXDpvJq_iE',
    appId: '1:331143083816:ios:5a8696084952797939021d',
    messagingSenderId: '331143083816',
    projectId: 'ishtopchi-216b8',
    storageBucket: 'ishtopchi-216b8.firebasestorage.app',
    iosClientId: '331143083816-kir3q80qqfi63k3ons61ak2sat8n8pdj.apps.googleusercontent.com',
    iosBundleId: 'torex.top.ishtopchi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3XPBiyBE99qcN8JglMfGz4CYl3js8JQk',
    appId: '1:331143083816:web:c51b491ffb654a4e39021d',
    messagingSenderId: '331143083816',
    projectId: 'ishtopchi-216b8',
    authDomain: 'ishtopchi-216b8.firebaseapp.com',
    storageBucket: 'ishtopchi-216b8.firebasestorage.app',
    measurementId: 'G-ZWQLZ8YLD0',
  );
}
